#pragma once

#define SYS_EPERM    (-1L)
#define SYS_ENOENT   (-2L)
#define SYS_ESRCH    (-3L)
#define SYS_EINTR    (-4L)
#define SYS_EIO      (-5L)
#define SYS_EBADF    (-9L)
#define SYS_ECHILD   (-10L)
#define SYS_EAGAIN   (-11L)
#define SYS_ENOMEM   (-12L)
#define SYS_EACCES   (-13L)
#define SYS_EFAULT   (-14L)
#define SYS_EBUSY    (-16L)
#define SYS_EEXIST   (-17L)
#define SYS_ENODEV   (-19L)
#define SYS_ENOTDIR  (-20L)
#define SYS_EISDIR   (-21L)
#define SYS_EINVAL   (-22L)
#define SYS_ENFILE   (-23L)
#define SYS_EMFILE   (-24L)
#define SYS_ENOSPC   (-28L)
#define SYS_ESPIPE   (-29L)
#define SYS_EPIPE    (-32L)
#define SYS_ERANGE   (-34L)
#define SYS_ENAMETOOLONG (-36L)
#define SYS_ENOSYS   (-38L)
